### ISSUE TITLE
Great software, but seems to have stopped working after release 1.0.5

### ISSUE THREAD

**Issue by hellisafish** [jpiquot/ChildTasksTemplate#2]
This was working brilliantly for me on Friday and has been really valuable, we have a selection of tasks added automatically.

After the automatic AzureDevOps update, I can still see the extension and its settings.
I can change the template json.
I can see the "Add tasks" button in the product backlog item menu, **BUT** when I select it, literally nothing happens.

I have tried from the product backlog list and tried from within the product backlog item.
I have tried different varieties of whether it is the template containing illegal characters etc, but even your example template doesn't work.
I have looked at different states of the story, but it doesn't seem to work for ANY existing product backlog items.
I have tried clearing all local browser caches etc, and reviewed authentication credentials etc.

It typically use Chrome, but when using Edge I get the following error on console when selecting the button

{description: "Assignment to read-only properties is not allowed in strict mode", message: "Assignment to read-only properties is not allowed in strict mode", name: "TypeError", number: -2146823243, stack: "TypeError: Assignment to read-only properties is not allowed in strict mode at u.setFieldValue (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.5/1607858620668/dist/extension.js:8:12810) at u.setFieldValue (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.5/1607858620668/dist/extension.js:8:12752) at u.setFieldValue (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.5/1607858620668/dist/extension.js:8:12752) at u.interpolate (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.5/1607858620668/dist/extension.js:8:12568) at Anonymous function (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.5/1607858620668/dist/extension.js:8:12231) at Generator.prototype.next (native code) at s (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.5/1607858620668/dist/extension.js:8:10980)"...}

Any help diagnosing the problem would be much appreciated

Thanks

Michael

**Comment by jpiquot** [comment]
Hi,

Do you see any error in the Chrome console?

Regards,
Jérôme

**Comment by jpiquot** [comment]
Could you tell me if you have this issue with version 1.0.6. Does it work with the démo template? [Template](https://github.com/jpiquot/ChildTasksTemplate/blob/main/static/demoTemplate.json)

**Comment by dylanjaye** [comment]
Good morning,

Our organization is having similar trouble when trying to generate child work items from a PBI using the ADO Scrum template.  We are using the demo JSON template included in the documentation.  We've noticed that the extension fails specifically on creating child work items from a PBI, but is able to successfully create child work items from another work item.

Here is the stack track that appears in the console when trying to create child tasks from a PBI:

"TypeError: Cannot create property 'Done' on string 'Approved'
    at Function.setFieldValue (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.6/1608211811175/dist/extension.js:8:13634)
    at Function.setFieldValue (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.6/1608211811175/dist/extension.js:8:13574)
    at Function.setFieldValue (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.6/1608211811175/dist/extension.js:8:13574)
    at Function.interpolate (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.6/1608211811175/dist/extension.js:8:13387)
    at p.<anonymous> (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.6/1608211811175/dist/extension.js:8:13013)
    at Generator.next (<anonymous>)
    at s (https://fiveforty.gallerycdn.vsassets.io/extensions/fiveforty/childtaskstemplate/1.0.6/1608211811175/dist/extension.js:8:11521)"

**Comment by jpiquot** [comment]
Hi, this has been fixed in version 1.0.7 (april 11)
