### ISSUE TITLE
Nested Template configuration

### ISSUE THREAD

**Issue by hans-wirz** [jpiquot/ChildTasksTemplate#4]
Hi 
I desperately need the ability to create a whole Tree of Work Items (Epic (as root Work Item) --> Features as childs, Features --> Stories as childs, Stories --> Tasks as childs)
Is it possible to nest the JSON configuration to achieve the automatic generation of such as Work Item Tree?

**Comment by jpiquot** [comment]
Hi,

As Epics, Features and User stories are very dependent on the business cases, this has not been planned. We will release the version 2.0.0 that will be a multi-template version. It may help to do less manual work but does not cover your request.

**Comment by kirk-quinbar** [comment]
I saw this as a closed item, but thought i'd add my +1 to this suggestion. We too have a similar need as it would be nice to automatically generate a feature with associated child pbi items. 
thanks..
