### ISSUE TITLE
UI bugs with the json editor

### ISSUE THREAD

**Issue by kirk-quinbar** [jpiquot/ChildTasksTemplate#7]
first off, we love this extension. It serves our needs perfectly. I am reporting a small UI bug i noticed with the json editor.

- There are some non-english characters in the dropdown that switches from tree to text
- There are some non-english characters in the breadcrumb after selecting a node

see attached
![2021-06-09 10_16_49-Settings · Child Tasks Template (Data) - Settings](https://user-images.githubusercontent.com/30601457/121383222-e7c26780-c90c-11eb-88bb-8b9a8a07686a.png)

**Comment by jpiquot** [comment]
thanks for your feedback. I use the javascript jsoneditor library. I opened an issue on their github repository : [1342](https://github.com/josdejong/jsoneditor/issues/1342)

**Comment by jpiquot** [comment]
Fixed in version 2.0.4
