### ISSUE TITLE
How can I work with custom WorkItemTypes?

### ISSUE THREAD

**Issue by SzilardVigh** [jpiquot/ChildTasksTemplate#8]
I was trying to use the following configuartion
`{
name: "System.WorkItemType"
value: "Review"
}
`
Review is a custom work item type created in an inherited process.

If I run this configurations, I'm getting the error message that says the Review is not allowed for System.WorkItemType.
I have check the details of a custom type and there the System.WorkItemType has the Review value.

Could you guide me please?
Thanks

**Comment by jpiquot** [comment]
Did you check your custom work item name with the API?

[Rest API WorkItem types](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20item%20types%20field/list?view=azure-devops-rest-6.0)
